version: '3.9'

services:
  api:
    build: .
    container_name: skillwizard-compiler-api
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/skill_wizard
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:7.0
    container_name: skillwizard-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: skillwizard-redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--save", "60", "1"]

volumes:
  mongo-data:
